#!/usr/bin/env python

from urllib.parse import urlparse
import os
import sys

components = urlparse(sys.argv[1])
url = '"https://mail.google.com/mail/?view=cm&fs=1&tf=1&source=mailto&to=' + components.path
if components.query:
    url = url + '&' + components.query.replace('subject', 'su')
url = url + '"'
os.system('xdg-open ' + url)
