#!/bin/bash

uptime=$(echo -n $(uptime | tr ',' ' ' | sed -e 's/.*average://'|awk '{print $1,$2,$3}'))
charging=1
percentage_remaining=""
percentage_remaining_string=""
lb="["
rb="]"

if [[ $(uname -o) == "Android" ]]
then
  battery_status_json=$(mktemp)
  termux-battery-status > $battery_status_json
  status=$(cat $battery_status_json | jq ".status")
  if [[ "$status" == "\"DISCHARGING\"" ]]
  then
    charging=0
  fi
  percentage_remaining=$(cat $battery_status_json | jq ".percentage")
  echo $percentage_remaining
else
  base_dir=/sys/bus/acpi/drivers/battery/PNP0C0A:0*/power_supply/*

  energy_now_file=$base_dir/energy_now
  test -e $energy_now_file && energy_now=$(cat $energy_now_file | paste -d + -s | bc)

  energy_full_file=$base_dir/energy_full
  test -e $energy_full_file && energy_full=$(cat $energy_full_file | paste -d + -s | bc)

  test -n "$energy_now" \
    && \
    test -n "$energy_full" \
    && \
    percentage_remaining=$(echo "scale=3; 100 * ($energy_now / $energy_full)" | bc | sed -e "s/\..*//")

  status_file=$base_dir/status
  test -e $status_file && cat $status_file | grep Discharging > /dev/null 2>&1 && charging=0

fi

if [[ charging -eq 0 ]]
then
  lb="{"
  rb="}"
fi

test -n "$percentage_remaining" && percentage_remaining_string="$lb$percentage_remaining%$rb"

echo "$uptime  $percentage_remaining_string"
