#!/bin/sh

base_dir=/sys/bus/acpi/drivers/battery
energy_now=$(cat $base_dir/PNP0C0A:0*/power_supply/*/energy_now | paste -d + -s | bc)
energy_full=$(cat $base_dir/PNP0C0A:0*/power_supply/*/energy_full | paste -d + -s | bc)
echo -n $(uptime | tr ',' ' ' | sed -e 's/.*average://'|awk '{print $1,$2,$3}')"  "
echo "scale=3; 100 * ($energy_now / $energy_full)" | bc | sed -e "s/\..*/\%/"
